# Generated by Django 3.0.5 on 2023-10-15 03:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('credentials', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='biometric',
        ),
    ]
