# Generated by Django 3.0.5 on 2023-10-08 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='frontimage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(upload_to='fimage')),
                ('names', models.CharField(max_length=250)),
                ('names2', models.CharField(max_length=250)),
                ('descs', models.TextField()),
            ],
        ),
    ]
