# Generated by Django 3.0.5 on 2023-11-18 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='doctor_id',
            new_name='doctor',
        ),
        migrations.RenameField(
            model_name='appointment',
            old_name='patient_id',
            new_name='patient',
        ),
        migrations.RenameField(
            model_name='doctor',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='patientdischargedetails',
            old_name='appointment_id',
            new_name='appointment',
        ),
    ]
