# Generated by Django 3.0.5 on 2023-11-19 06:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0003_auto_20231119_1126'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorLeave',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('leave_day', models.DateTimeField()),
                ('partial_leave', models.BooleanField(default=False)),
                ('partial_time_on_leave_start', models.TimeField(blank=True, null=True)),
                ('partial_time_on_leave_end', models.TimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_leave', to='hospital.Doctor')),
            ],
        ),
    ]
