# Generated by Django 3.0.5 on 2023-11-19 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0005_holidays'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorleave',
            name='reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
