# Generated by Django 3.0.5 on 2023-10-15 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='d_register',
            new_name='dregister',
        ),
    ]
