# Generated by Django 3.0.5 on 2023-10-15 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0002_auto_20231015_1857'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dregister',
            old_name='username',
            new_name='uname',
        ),
    ]
